payload = {"requests": [{"id": "0", "queryName": "lastUpdate", "single": True, "parameters": {}},
                        {"id": "1", "queryName": "infectedPerDate", "single": False, "parameters": {}},
                        {"id": "2", "queryName": "updatedPatientsOverallStatus", "single": False, "parameters": {}},
                        {"id": "3", "queryName": "sickPerDateTwoDays", "single": False, "parameters": {}},
                        {"id": "4", "queryName": "sickPatientPerLocation", "single": False, "parameters": {}},
                        {"id": "5", "queryName": "patientsStatus", "single": False, "parameters": {}},
                        {"id": "6", "queryName": "updatedPatientsOverallStatus", "single": False, "parameters": {}},
                        {"id": "7", "queryName": "patientsPerDate", "single": False, "parameters": {}},
                        {"id": "8", "queryName": "vaccinated", "single": False, "parameters": {}},
                        {"id": "9", "queryName": "deadPatientsPerDate", "single": False, "parameters": {}},
                        {"id": "10", "queryName": "testResultsPerDate", "single": False, "parameters": {}},
                        {"id": "11", "queryName": "vaccinationsPerAge", "single": False, "parameters": {}},
                        {"id": "12", "queryName": "infectedPerDate", "single": False, "parameters": {}},
                        {"id": "13", "queryName": "doublingRate", "single": False, "parameters": {}},
                        {"id": "14", "queryName": "testResultsPerDate", "single": False, "parameters": {}},
                        {"id": "15", "queryName": "testsPerDate", "single": False, "parameters": {}},
                        {"id": "16", "queryName": "testsPerDate", "single": False, "parameters": {}},
                        {"id": "17", "queryName": "patientsPerDate", "single": False, "parameters": {}},
                        {"id": "18", "queryName": "patientsPerDate", "single": False, "parameters": {}},
                        {"id": "19", "queryName": "infectedPerDate", "single": False, "parameters": {}},
                        {"id": "20", "queryName": "patientsPerDate", "single": False, "parameters": {}},
                        {"id": "21", "queryName": "cumSeriusAndBreath", "single": False, "parameters": {}},
                        {"id": "22", "queryName": "averageInfectedPerWeek", "single": False, "parameters": {}},
                        {"id": "23", "queryName": "infectedPerDate", "single": False, "parameters": {}},
                        {"id": "24", "queryName": "infectedPerDate", "single": False, "parameters": {}},
                        {"id": "25", "queryName": "deadPatientsPerDate", "single": False, "parameters": {}},
                        {"id": "26", "queryName": "spotlightLastupdate", "single": False, "parameters": {}},
                        {"id": "27", "queryName": "spotlightAggregatedPublic", "single": True, "parameters": {}},
                        {"id": "28", "queryName": "spotlightLastupdate", "single": False, "parameters": {}},
                        {"id": "29", "queryName": "testResultsPerDate", "single": False, "parameters": {}},
                        {"id": "30", "queryName": "LastWeekLabResults", "single": False, "parameters": {}},
                        {"id": "31", "queryName": "contagionDataPerCityPublic", "single": False, "parameters": {}},
                        {"id": "32", "queryName": "deadPatientsPerDate", "single": False, "parameters": {}},
                        {"id": "33", "queryName": "infectedPerDate", "single": False, "parameters": {}},
                        {"id": "34", "queryName": "HospitalBedStatusSegmentation", "single": False, "parameters": {}},
                        {"id": "35", "queryName": "infectedByAgeAndGenderPublic", "single": False,
                         "parameters": {"ageSections": [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]}},
                        {"id": "36", "queryName": "isolatedVerifiedDoctorsAndNurses", "single": False,
                         "parameters": {}},
                        {"id": "37", "queryName": "hospitalStatus", "single": False, "parameters": {}},
                        {"id": "38", "queryName": "vaccinated", "single": False, "parameters": {}},
                        {"id": "39", "queryName": "vaccinated", "single": False, "parameters": {"days": 0}},
                        {"id": "40", "queryName": "vaccinated", "single": False, "parameters": {"days": 0}},
                        {"id": "41", "queryName": "doublingRate", "single": False, "parameters": {}},
                        {"id": "42", "queryName": "patientsPerDate", "single": False, "parameters": {}},
                        {"id": "43", "queryName": "updatedPatientsOverallStatus", "single": False, "parameters": {}},
                        {"id": "44", "queryName": "CalculatedVerified", "single": False, "parameters": {}},
                        {"id": "45", "queryName": "spotlightPublic", "single": False, "parameters": {}}]}

queries = {}
for request in payload["requests"]:
    queries[request["queryName"]] = True

print('\n'.join(sorted(queries.keys())))
